name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        # Вот эта строка говорит роботу зайти в твою папку перед сборкой:
        run: |
          cd "Desktop/Projects/FastAPI"
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-fastapi-app:latest
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build -t $IMAGE_ID .
          docker push $IMAGE_ID
